### ISSUE TITLE
archivos de udev en path incorrecto

### ISSUE THREAD

**Issue by ftoledo** [HuayraLinux/icaro#2]
Las reglas de udev deben ir en /lib/udev.d 

<pre>
E: icaro: udev-rule-in-etc etc/udev/rules.d/026-microchip.rules
E: icaro: udev-rule-in-etc etc/udev/rules.d/26-microchip.rules
E: icaro: udev-rule-in-etc etc/udev/rules.d/41-microchip.rules
E: icaro: udev-rule-in-etc etc/udev/rules.d/99-mm-usb-device-blacklist.rules
E: icaro: udev-rule-in-etc etc/udev/rules.d/99-serial.rules
</pre>

**Comment by ftoledo** [comment]
Los nombres de los enlances de udev deberian tener algun prefijo por ejemplo:

 "99-**icaro**-serial.rules"

Porque los nombre son muy genericos y tiene conflictos con otros paquetes.

mm-usb-device-blacklit.rules está actualmente en modemmanager y genera error

**Comment by iglosiggio** [comment]
Ahora en un rato lo clono y los prefijo ^^

**Comment by iglosiggio** [comment]
d4bd294057e8bfe4cd8f4fedebede9866b0e9f60 fijate ahí

**Comment by iglosiggio** [comment]
Supongo que con tu último commit (76b95fa) ya se puede cerrar no?
